#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Openwrt
# Redsocks2 启动脚本

START=90
APP=redsocks2
PID_FILE=/var/run/$APP.pid
CFG_FILE=/etc/redsocks2.conf

start() {
	service_start /usr/sbin/redsocks2 -c $CFG_FILE -p $PID_FILE
}

stop() {
	service_stop /usr/sbin/redsocks2 && rm -rf $PID_FILE
}
