#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99
STOP=10

monitor() {
	if [ ! -f "/etc/crontabs/root" ] || [ -z "$(cat /etc/crontabs/root | grep proxymonitor)" ]; then
  		sed -i '/proxymonitor/d' /etc/crontabs/root >/dev/null 2>&1
  		echo "*/5 * * * * /etc/proxymonitor.sh" >> /etc/crontabs/root 
	fi
}

boot() {
	start
	monitor
}

load_firewall() {
	iptables -t nat -N PROXY
	iptables -t nat -A PROXY -d 0.0.0.0/8 -j RETURN
	iptables -t nat -A PROXY -d 10.0.0.0/8 -j RETURN
	iptables -t nat -A PROXY -d 11.11.0.0/16 -j RETURN
	iptables -t nat -A PROXY -d 127.0.0.0/8 -j RETURN
	iptables -t nat -A PROXY -d 169.254.0.0/16 -j RETURN
	iptables -t nat -A PROXY -d 172.16.0.0/12 -j RETURN
	iptables -t nat -A PROXY -d 192.168.0.0/16 -j RETURN
	iptables -t nat -A PROXY -d 224.0.0.0/4 -j RETURN
	iptables -t nat -A PROXY -d 240.0.0.0/4 -j RETURN
	# iptables -t nat -A PROXY -p tcp --dport 443 -j REDIRECT --to-ports 8080
	iptables -t nat -A PROXY -p tcp -j REDIRECT --to-ports 8088
	iptables -t nat -A PROXY -p udp -j REDIRECT --to-ports 8088
	iptables -t nat -A PROXY -p icmp -j REDIRECT --to-ports 8088
	# iptables -t nat -I zone_lan_prerouting -j PROXY
	iptables -t nat -A PREROUTING -j PROXY
	iptables -t nat -A OUTPUT -p tcp -j PROXY
}

flush_firewall() {
	iptables -t nat -F PROXY
	iptables -t nat -D PREROUTING -j PROXY
	iptables -t nat -D OUTPUT -p tcp -j PROXY
}

start()
{
	load_firewall
	echo  "tproxy start complete"
}

stop()
{
	flush_firewall
}
